---
#
# Maintain the /etc/hosts file

- name: Updating the /etc/hosts file
  hosts: all
  become: yes

  tasks:
    - name: installing updated /etc/hosts file
      ansible.builtin.copy:
        src: "file/etc.hosts"
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
        backup: yes
      notify: restart dnsmasq
      tags: dnsmasq

  handlers:
  
    - name: restart dnsmasq
      ansible.builtin.service:
        name: /etc/init.d/dnsmasq
        state: restarted
        enabled: yes
