---
#
# Maintain the /etc/hosts file

- name: Updating the /etc/hosts file
  hosts: gatekeeper
  become: yes

  tasks:
    - name: installing updated /etc/hosts file
      ansible.builtin.copy:
        src: "/home/eames/github/lab-setup/gatekeeper/file/etc.hosts"
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
        backup: yes
      notify: restart dnsmasq
      tags: dnsmasq

  handlers:
  
    - name: restart dnsmasq
      ansible.builtin.service:
        name: dnsmasq
        state: restarted
        enabled: yes

    - name: restart dhcp # provided by dnsmasq
      ansible.builtin.service:
        name: dnsmasq
        state: restarted
        enabled: yes
